<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Siswa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->database();
        $this->load->model('Siswa_model');
    } 

    /*
     * Listing of siswa
     */
    function index()

    {
        $data['title']='listsiswa';
        $data['page']='index';
        $data['siswa'] = $this->Siswa_model->get_all_siswa();
        
        $data['_view'] = 'siswa/index';
        $this->rendersiswa($data);
    }

    /*
     * Adding a new siswa
     */
    function add()
    {   
        $data['title']='listsiswa';
        $data['page']='add';
        $this->rendersiswa($data);

        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'nisn' => $this->input->post('nisn'),
                'nama_siswa' => $this->input->post('nama_siswa'),
                'id_kelas' => $this->input->post('id_kelas'),
				'jenis_kelamin' => $this->input->post('jenis_kelamin'),
                'alamat' => $this->input->post('alamat'),
                'no_hp' => $this->input->post('no_hp'),             
				

            );
            
            $siswa_id = $this->Siswa_model->add_siswa($params);
            redirect('Siswa/index');
        }
        else
        {            
            // $data['_view'] = 'siswa/add';
            // $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a antrian
     */
    function edit()

    {    
        // check if the siswa exists before trying to edit it
        // $data['Siswa'] = $this->Siswa_model->get_siswa($nisn);
        
        if(isset($data['Siswa']['nisn']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nisn' => $this->input->post('nisn'),
                    'nama_siswa' => $this->input->post('nama_siswa'),
                    'id_kelas' => $this->input->post('id_kelas'),
                    'jenis_kelamin' => $this->input->post('jenis_kelamin'),
                    'alamat' => $this->input->post('alamat'),
                    'no_hp' => $this->input->post('no_hp'),         
                );

                $this->Siswa_model->update_siswa($nisn,$params);            
                redirect('Siswa/index');
            }
            else
            {     
           $data['title']='listsiswa';
           $data['page']='edit';
           $data['_view'] = 'Siswa/edit';
               $this->rendersiswa ($data);
                
                  // $this->load->view('layouts/main',$data);
                   
                  
            }
        }
        else
            show_error('The Siswa you are trying to edit does not exist.');
    } 

    /*
     * Deleting siswa
     */
    function remove($nisn)
    {
        $siswa = $this->Siswa_model->get_siswa($nisn);

        // check if the siswa exists before trying to delete it
        if(isset($siswa['nisn']))
        {
            $this->Siswa_model->delete_siswa($nisn);
            redirect('Siswa/index');
        }
        else
            show_error('The Siswa you are trying to delete does not exist.');
    }

    public function rendersiswa($data){
        $this->load->view('bayar/header');
        $this->load->view('bayar/maincontent',$data);
        $this->load->view('bayar/footer');
    }


}
