<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Siswa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get siswa by id_siswa
     */
    function get_siswa($nisn)
    {
        return $this->db->get_where('Siswa',array('nisn'=>$nisn))->row_array();
    }
        
    /*
     * Get all siswa
     */
    function get_all_siswa()
    {
        $this->db->order_by('nisn', 'ASC');
        return $this->db->get('Siswa')->result_array();
    }
        
    /*
     * function to add new Siswa
     */
    function add_siswa($params)
    {
        $this->db->insert('Siswa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update Siswa
     */
    function update_siswa($nisn,$params)
    {
        $this->db->where('nisn',$nisn);
        return $this->db->update('Siswa',$params);
    }
    
    /*
     * function to delete siswa
     */
    function delete_siswa($nisn)
    {
        return $this->db->delete('Siswa',array('nisn'=>$nisn));
    }
}
